/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardProdus: typeof import('./src/components/CardProdus.vue')['default']
    CardProdusContainer: typeof import('./src/components/CardProdusContainer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
