/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardInfo: typeof import('./src/components/CardInfo.vue')['default']
    CardProdus: typeof import('./src/components/CardProdus.vue')['default']
    CarouselImg: typeof import('./src/components/CarouselImg.vue')['default']
    FooterLayout: typeof import('./src/components/FooterLayout.vue')['default']
    Navbar: typeof import('./src/components/navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollToTop: typeof import('./src/components/scrollToTop.vue')['default']
    SnackBarMsg: typeof import('./src/components/SnackBarMsg.vue')['default']
    SocialBtn: typeof import('./src/components/SocialBtn.vue')['default']
  }
}
