/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/CartView': RouteRecordInfo<'/CartView', '/CartView', Record<never, never>, Record<never, never>>,
    '/ContactView': RouteRecordInfo<'/ContactView', '/ContactView', Record<never, never>, Record<never, never>>,
    '/HomeView': RouteRecordInfo<'/HomeView', '/HomeView', Record<never, never>, Record<never, never>>,
    '/ListenDownView': RouteRecordInfo<'/ListenDownView', '/ListenDownView', Record<never, never>, Record<never, never>>,
    '/ProductDetail': RouteRecordInfo<'/ProductDetail', '/ProductDetail', Record<never, never>, Record<never, never>>,
    '/StoreView': RouteRecordInfo<'/StoreView', '/StoreView', Record<never, never>, Record<never, never>>,
    '/StudioView': RouteRecordInfo<'/StudioView', '/StudioView', Record<never, never>, Record<never, never>>,
  }
}
